FROM python:3.8.6-buster

COPY api /api
COPY api/model_logistic_regression_Army_present_at_event /model_logistic_regression_Army_present_at_event
COPY api/model_logistic_regression_Arrests__detentions /model_logistic_regression_Arrests__detentions
COPY api/model_logistic_regression_Deaths_inflicted /model_logistic_regression_Deaths_inflicted
COPY api/model_logistic_regression_Injuries_inflicted /model_logistic_regression_Injuries_inflicted
COPY api/model_logistic_regression_No_known_coercion_no_security_presence /model_logistic_regression_No_known_coercion_no_security_presence
COPY api/model_logistic_regression_Party_Militias_Baltagia_present_at_event /model_logistic_regression_Party_Militias_Baltagia_present_at_event
COPY api/model_logistic_regression_Physical_harassment /model_logistic_regression_Physical_harassment
COPY api/model_logistic_regression_Security_forces_present_at_event /model_logistic_regression_Security_forces_present_at_event
COPY requirements.txt /requirements.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD uvicorn api.api:app --host 0.0.0.0 --port $PORT
